# Occupant Responsive Buildings
# https://github.com/cweyandt/orb
# Base docker image for running ORB framework
# Created 2020-06-16, cweyandt@berkeley.edu

---
version: "3.9"

services:
  orb:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.orb
    volumes:
      - "./data:/home/jovyan/data"
    expose:
      - "5000"
    ports:
      - "8080:5000"
    stdin_open: true
    tty: true
    # command: ["./api.py"]

  jupyterlab:
    # image: jupyter/tensorflow-notebook
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.jupyter
    volumes:
      - "./data:/home/jovyan/data"
      - "./:/home/jovyan/orb_local"
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    environment:
      JUPYTER_ENABLE_LAB: "yes"

  # web:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/Dockerfile.web
  #   volumes:
  #     - "./web:/web"
  #   ports: 
  #     - "80:5000"
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     FLASK_ENV: "development"
  #     FLASK_APP: "web_app.py"
  #     # FLASK_RUN_HOST: "0.0.0.0"
  #   # command: ["cd","/usr/src/app"]
  #   # command: python3 -m http.server 5000 --bind 127.0.0.1
  #   # command: ["flask", "run"]


#https://gist.github.com/cboettig/8643341bd3c93b62b5c2
  nginx:  
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.nginx
    # links: 
    #   - orb
    #   - jupyter
    # volumes:
      # - ./docker/nginx.conf:/etc/nginx/nginx.conf
      # - ./letsencrypt.crt:/data/cert.crt
      # - /letsencrypt.key:/data/key.key
      # - ./04_Website:/usr/share/nginx/html
    ports:
      - "80:80"
      # - "443:443"