# Occupant Responsive Buildings
# https://github.com/cweyandt/orb
# Base docker image for running ORB framework
# Created 2020-06-16, cweyandt@berkeley.edu

---
version: "3.9"

services:
  orb:
    build: 
      context: ./
      dockerfile: ./pipeline/orb/Dockerfile
    volumes:
      - "./data:/home/jovyan/data"
    ports:
      - "443:443"
      - "80:80"
    stdin_open: true
    tty: true
    # command: ["./api.py"]

  jupyterlab:
    # image: jupyter/tensorflow-notebook
    build: 
      context: ./
      dockerfile: ./pipeline/jupyterlab/Dockerfile
    volumes:
      - "./data:/home/jovyan/data"
      - "./:/home/jovyan/orb_local"
    ports:
      - "8888:8888"
    stdin_open: true
    tty: true
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      PASSWORD: ${PASSWORD}
#    command: ["./main.py", "maskDetector", "--log-level", "debug"]


# https://gist.github.com/cboettig/8643341bd3c93b62b5c2
  # nginx:  
  #   image: nginx
  #   links: 
  #     - orb
  #     - jupyter
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./letsencrypt.crt:/data/cert.crt
  #     - /letsencrypt.key:/data/key.key
  #   ports:
  #     - 80:80
  #     - 443:443