# Occupant Responsive Buildings
# https://github.com/cweyandt/orb
# Base docker image for running ORB framework
# Created 2020-06-16, cweyandt@berkeley.edu

---
version: "3.9"

services:
  # FastAPI instance running changepoint inference at /api/v1
  # Interactive Swagger documentation at /api/v1/doc
  orb:
    build: 
      context: ./
      dockerfile: docker/orb.dockerfile
    volumes:
      - "./src:/app"
      - "./data:/data"
    expose:
      - "80"
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    environment:
      PORT: 80
      LOG_LEVEL: debug # This doesn't work properly with the following start-reload.sh enabled
    restart: always
    # Comment next line for production, it causes the server to auto-reload on file changes.
    command: ["/start-reload.sh"]

  # Basic Jupyter Lab instance with TensorFlow libraries pre-installed
  jupyterlab:
    build:
      context: ./
      dockerfile: docker/jupyterlab.dockerfile
    volumes:
      - "./data:/home/jovyan/data"
      - "./src:/home/jovyan/orb"
    ports:
      - "8888:8888"
    expose:
      - "8888"
    stdin_open: true
    tty: true
    environment:
      JUPYTER_ENABLE_LAB: "yes"

  # NGINX container configuration
  # Serves exposed ports on previous containers via HTTP/TCP:80
  # TODO: Implement SSL
  # TODO: Implement proxy pass for jupyter notebooks? (this may not be desirable for security reasons)
  # https://gist.github.com/cboettig/8643341bd3c93b62b5c2
  nginx:  
    build: 
      context: ./
      dockerfile: docker/nginx.dockerfile
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html
      # - ./letsencrypt.crt:/data/cert.crt
      # - ./letsencrypt.key:/data/key.key
    ports:
      - "80:80"
      # - "443:443"
    links:
      - "jupyterlab"
      - "orb"
