# Occupant Responsive Buildings
# https://github.com/cweyandt/orb
# Base docker image for running ORB framework
# Created 2020-06-16, cweyandt@berkeley.edu

---
version: "3.9"

services:
  orb:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.orb
#    volumes:
#      - "./data:/home/jovyan/data"
    expose:
      - "80"
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
#    command: ["python3", "/home/jovyan/orb/simple_app.py"]
    environment:
      PORT: 80
      LOG_LEVEL: "debug"

  jupyterlab:
    # image: jupyter/tensorflow-notebook
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.jupyter
    volumes:
      - "./data:/home/jovyan/data"
      - "./:/home/jovyan/orb_local"
    #ports:
    #  - "8888:8888"
    expose:
      - "8888"
    stdin_open: true
    tty: true
    environment:
      JUPYTER_ENABLE_LAB: "yes"


  #https://gist.github.com/cboettig/8643341bd3c93b62b5c2
  nginx:  
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile.nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web:/usr/share/nginx/html
      # - ./letsencrypt.crt:/data/cert.crt
      # - ./letsencrypt.key:/data/key.key
    ports:
      - "80:80"
      # - "443:443"
    links:
      - "jupyterlab"
      - "orb"


  # web:
  #   build:
  #     context: ./
  #     dockerfile: ./docker/Dockerfile.web
  #   volumes:
  #     - "./web:/web"
  #   ports: 
  #     - "80:5000"
  #   stdin_open: true
  #   tty: true
  #   environment:
  #     FLASK_ENV: "development"
  #     FLASK_APP: "web_app.py"
  #     # FLASK_RUN_HOST: "0.0.0.0"
  #   # command: ["cd","/usr/src/app"]
  #   # command: python3 -m http.server 5000 --bind 127.0.0.1
  #   # command: ["flask", "run"]