FROM python:3-alpine
MAINTAINER Chris Weyandt <cweyandt@berkeley.edu> 

COPY docker/requirements.web requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /web

CMD [ "python", "web_app.py" ]

